run:
  deadline: 5m
  skip-dirs:
    - pkg/acme/x
    - pkg/common

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - varcheck
