run:
  timeout: 5m
issues:
  exclude-dirs:
    - pkg/acme/x
    - pkg/common
    - pkg/controller/legacy
linters:
  enable:
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
