blank_issues_enabled: true
contact_links:
- name: Slack
  url: https://kubernetes.slack.com/channels/n42-gateway
  about: "We're in the #n42-gateway channel on Kubernetes Slack. Take an invite at https://slack.k8s.io if not subscribed yet."
- name: Discussions
  url: https://github.com/n42-gateway/n42-gateway/discussions
  about: "Follow announcements and ask questions on GitHub Discussions."
