name: "Close stale issues"
on:
  schedule:
  - cron: "0 10 * * 1"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue got stale and will be closed in 7 days.'
        stale-issue-label: 'lifecycle/stale'
        exempt-issue-labels: 'lifecycle/backlog'
        days-before-stale: 30
        days-before-close: 6
